# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID

filter_out_cod_start_users: True

inter_file_name: 'sports.inter'

# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'
#text_feature_file: 'item_cf_embeds_Norm_Mistral-7B-v0.1_array.npy'
user_graph_dict_file: 'user_graph_dict.npy'

field_separator: "\t"
